import { Order } from "@/types/order"

export const inProgressOrders: Order[] = [
    {
        id: "1001",
        status: "in_progress",
        createdAt: "2025-08-01T10:30:00Z",
        totalPrice: 350000,
        customerId: "u1",
        products: [
            {
                id: "p1",
                title: "کیبورد مکانیکال گیمینگ",
                description: "کیبورد مکانیکال با نورپردازی RGB و کلیدهای مکانیکال قرمز",
                category: "لوازم جانبی کامپیوتر",
                price: 150000,
                discountPercentage: 0,
                rating: 4.8,
                stock: 15,
                tags: ["گیمینگ", "کیبورد"],
                brand: "Redragon",
                sku: "KB-101",
                weight: 900,
                dimensions: { width: 45, height: 5, depth: 15 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-30T08:00:00Z",
                    updatedAt: "2025-07-31T08:00:00Z",
                    barcode: "123456789012",
                    qrCode: "QR123"
                },
                thumbnail: "/images/keyboard.jpg",
                images: ["/images/keyboard.jpg"],
                quantity: 1,
                unitPrice: 150000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
        ]
    },
    {
        id: "1041",
        status: "in_progress",
        createdAt: "2025-08-01T10:30:00Z",
        totalPrice: 350000,
        customerId: "u1",
        products: [
            {
                id: "p1",
                title: "کیبورد مکانیکال گیمینگ",
                description: "کیبورد مکانیکال با نورپردازی RGB و کلیدهای مکانیکال قرمز",
                category: "لوازم جانبی کامپیوتر",
                price: 150000,
                discountPercentage: 0,
                rating: 4.8,
                stock: 15,
                tags: ["گیمینگ", "کیبورد"],
                brand: "Redragon",
                sku: "KB-101",
                weight: 900,
                dimensions: { width: 45, height: 5, depth: 15 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-30T08:00:00Z",
                    updatedAt: "2025-07-31T08:00:00Z",
                    barcode: "123456789012",
                    qrCode: "QR123"
                },
                thumbnail: "/images/keyboard.jpg",
                images: ["/images/keyboard.jpg"],
                quantity: 1,
                unitPrice: 150000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
        ]
    },
    {
        id: "1301",
        status: "in_progress",
        createdAt: "2025-08-01T10:30:00Z",
        totalPrice: 350000,
        customerId: "u1",
        products: [
            {
                id: "p1",
                title: "کیبورد مکانیکال گیمینگ",
                description: "کیبورد مکانیکال با نورپردازی RGB و کلیدهای مکانیکال قرمز",
                category: "لوازم جانبی کامپیوتر",
                price: 150000,
                discountPercentage: 0,
                rating: 4.8,
                stock: 15,
                tags: ["گیمینگ", "کیبورد"],
                brand: "Redragon",
                sku: "KB-101",
                weight: 900,
                dimensions: { width: 45, height: 5, depth: 15 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-30T08:00:00Z",
                    updatedAt: "2025-07-31T08:00:00Z",
                    barcode: "123456789012",
                    qrCode: "QR123"
                },
                thumbnail: "/images/keyboard.jpg",
                images: ["/images/keyboard.jpg"],
                quantity: 1,
                unitPrice: 150000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
            {
                id: "p2",
                title: "ماوس گیمینگ بی‌سیم",
                description: "ماوس بی‌سیم با دقت 16000 DPI و طراحی ارگونومیک",
                category: "لوازم جانبی کامپیوتر",
                price: 200000,
                discountPercentage: 0,
                rating: 4.6,
                stock: 10,
                tags: ["گیمینگ", "ماوس"],
                brand: "Logitech",
                sku: "MS-201",
                weight: 120,
                dimensions: { width: 6, height: 4, depth: 12 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 3 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-29T08:00:00Z",
                    updatedAt: "2025-07-30T08:00:00Z",
                    barcode: "987654321098",
                    qrCode: "QR456"
                },
                thumbnail: "/images/mouse.jpg",
                images: ["/images/mouse.jpg"],
                quantity: 1,
                unitPrice: 200000
            },
        ]
    },
]

export const completedOrders: Order[] = [
    {
        id: "1002",
        status: "completed",
        createdAt: "2025-07-20T12:00:00Z",
        totalPrice: 1200000,
        customerId: "u1",
        products: [
            {
                id: "p3",
                title: "لپ‌تاپ ایسوس مدل X515",
                description: "لپ‌تاپ ایسوس با پردازنده Core i5 و 8 گیگابایت رم",
                category: "لپ‌تاپ",
                price: 1200000,
                discountPercentage: 0,
                rating: 4.5,
                stock: 5,
                tags: ["لپ‌تاپ", "ایسوس"],
                brand: "ASUS",
                sku: "AS-X515",
                weight: 1500,
                dimensions: { width: 35, height: 2, depth: 24 },
                warrantyInformation: "18 ماه گارانتی",
                shippingInformation: "ارسال فوری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-15T08:00:00Z",
                    updatedAt: "2025-07-18T08:00:00Z",
                    barcode: "555666777888",
                    qrCode: "QR789"
                },
                thumbnail: "/images/laptop.jpg",
                images: ["/images/laptop.jpg"],
                quantity: 1,
                unitPrice: 1200000
            }
        ]
    }
]

export const cancelledOrders: Order[] = [
    {
        id: "1003",
        status: "cancelled",
        createdAt: "2025-07-25T09:15:00Z",
        totalPrice: 450000,
        customerId: "u1",
        products: [
            {
                id: "p4",
                title: "هدفون بلوتوثی سونی",
                description: "هدفون بی‌سیم با کیفیت صدای عالی و نویز کنسلینگ",
                category: "هدفون",
                price: 450000,
                discountPercentage: 0,
                rating: 4.7,
                stock: 8,
                tags: ["هدفون", "بی‌سیم"],
                brand: "Sony",
                sku: "SONY-BT1",
                weight: 250,
                dimensions: { width: 20, height: 5, depth: 20 },
                warrantyInformation: "یک سال گارانتی",
                shippingInformation: "ارسال 2 روز کاری",
                availabilityStatus: "in_stock",
                reviews: [],
                returnPolicy: "7 روز مهلت بازگشت",
                minimumOrderQuantity: 1,
                meta: {
                    createdAt: "2025-07-22T08:00:00Z",
                    updatedAt: "2025-07-23T08:00:00Z",
                    barcode: "111222333444",
                    qrCode: "QR999"
                },
                thumbnail: "/images/headphone.jpg",
                images: ["/images/headphone.jpg"],
                quantity: 1,
                unitPrice: 450000
            }
        ]
    }
]
